name: CI

# run on all branches for PRs opened
on:
  pull_request:
    branches:
      - '**'

jobs:
  run-base-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: 8

      - name: Run Full Tests
        run: |
          ./gradlew clean check
